default:
    KAFKA_TOPIC: tweets
    KAFKA_ENDPOINT: 'localhost:9092'
    KAFKA_GROUP: 'tweets-group'
    TELEGRAM_BOT_API_KEY: '<empty>'
    TELEGRAM_BOT_TARGET_CHAT: '<empty>'
staging:
    KAFKA_TOPIC: tweets
