default:
    KAFKA_TOPIC: tweets
    KAFKA_ENDPOINT: 'localhost:9092'
    KAFKA_GROUP: 'tweets-group'
    TELEGRAM_BOT_API_KEY: '721276587:AAHh7D9YcRt5ms1eooPG8ptwOA-Hv0fWzgI'
    TELEGRAM_BOT_TARGET_CHAT: '470461156'
staging:
    KAFKA_TOPIC: tweets