default:
    KAFKA_TOPIC: tweets
    KAFKA_ENDPOINT: 'localhost:9092'
    TWITTER_KEY: '<empty>'
    TWITTER_SECRET: '<empty>'
    TWITTER_TOKEN_KEY: '<empty>'
    TWITTER_TOKEN_SECRET: '<empty>'
    TWITTER_TARGET_USER: '<empty>'
staging:
    TOPIC: tweets
